
const thesis = [
    {id: 0, title: "Title1", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 1, title: "Title2", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 2, title: "Title3", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 3, title: "Title4", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 4, title: "Title5", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 5, title: "Title6", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 6, title: "Title7", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 7, title: "Title8", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 8, title: "Title9", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 9, title: "Title10", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {id: 10, title: "Title11", supervisor:"Marco Torchiano", coSupervisors: "Torchiano Marco", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expirationDate: "2023/12/06", level: 3, programmes: "Don't know what it means"},
];

export {thesis};