
const thesis = [
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title2", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title3", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title4", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title5", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title6", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title7", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title8", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title9", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title10", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title11", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
];

export {thesis};