
const thesis = [
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
    {title: "Title1", supervisor:"Marco Torchiano", co_supervisor: "Marco Torchiano", keywords:"soundtrack", type:"se2", groups:"se", description:"Find a new soundtrack", required_knowledges: "musical culture", notes:"delusional attempt", expiration: "2023/12/06", level: 3, programmes: "Don't know what it means"},
];

export {thesis};