const students = [
  {
    email: "studente.team3@gmail.com",
    enrollment_year: "2023",
    surname: "Test",
    nationality: "Italian",
    cod_degree: "AB123CD",
    id: "s000000",
    name: "User",
    gender: "Male",
  },
  {
    email: "s345678@studenti.polito.it",
    enrollment_year: "2023",
    surname: "Ricci",
    nationality: "Italian",
    cod_degree: "QR345ST",
    id: "s345678",
    name: "Luca",
    gender: "Male",
  },
  {
    surname: "Martini",
    enrollment_year: "2021",
    email: "s678901@studenti.polito.it",
    id: "s678901",
    name: "Alessia",
    gender: "Female",
    nationality: "Italian",
    cod_degree: "QR345ST",
  },
  {
    name: "Valentina",
    enrollment_year: "2020",
    cod_degree: "MN012OP",
    gender: "Female",
    id: "s456789",
    email: "s456789@studenti.polito.it",
    nationality: "Italian",
    surname: "Romano",
  },
  {
    email: "s234567@studenti.polito.it",
    name: "Francesca",
    surname: "Bianchi",
    cod_degree: "AB123CD",
    enrollment_year: "2021",
    nationality: "Italian",
    id: "s234567",
    gender: "Female",
  },
  {
    name: "Marco",
    gender: "Male",
    nationality: "Italian",
    id: "s567890",
    surname: "Ferrari",
    enrollment_year: "2022",
    cod_degree: "IJ789KL",
    email: "s567890@studenti.polito.it",
  },
  {
    cod_degree: "IJ789KL",
    id: "s012345",
    nationality: "Italian",
    gender: "Female",
    email: "s012345@studenti.polito.it",
    surname: "Ferrara",
    enrollment_year: "2021",
    name: "Elena",
  },
  {
    enrollment_year: "2023",
    cod_degree: "IJ789KL",
    gender: "Male",
    nationality: "Italian",
    name: "Roberto",
    id: "s789012",
    email: "s789012@studenti.polito.it",
    surname: "Conti",
  },
  {
    id: "s890123",
    surname: "Gallo",
    cod_degree: "EF456GH",
    nationality: "Italian",
    email: "s890123@studenti.polito.it",
    gender: "Female",
    enrollment_year: "2020",
    name: "Laura",
  },
  {
    enrollment_year: "2019",
    nationality: "Italian",
    cod_degree: "AB123CD",
    name: "Giuseppe",
    surname: "Rossi",
    gender: "Male",
    id: "s123456",
    email: "s123456@studenti.polito.it",
  },
  {
    cod_degree: "AB123CD",
    name: "Simone",
    id: "s901234",
    gender: "Male",
    email: "s901234@studenti.polito.it",
    nationality: "Italian",
    surname: "Marino",
    enrollment_year: "2022",
  },
  {
    cod_degree: "UV246WZ",
    name: "Bryan",
    id: "s0000002",
    gender: "male",
    email: "s0000002@studenti.polito.it",
    nationality: "American",
    surname: "Woods",
    enrollment_year: "2021",
  },
  {
    cod_degree: "UV246WZ",
    name: "Elmo",
    id: "s0000001",
    gender: "male",
    email: "s0000001@studenti.polito.it",
    nationality: "British",
    surname: "Moss",
    enrollment_year: "2022",

  }
];

export default students;
