const thesisRequests = [
  {
    requestDate: "2020-05-06",
    approvalDate: "",
    approved: null,
    title: "Microstructural Characterization of Components for a Lunar Infrastructure",
    description: "This thesis aims to conduct a comprehensive microstructural characterization of components designed for use in lunar infrastructure",
    programmes: "Computer Enginnering",
    studentId: "s345678",
    teacherId: "d345678",
    notes: "",
    type: "Academic research",
    coSupervisors: [],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    type: "Academic research",
    notes: "",
    studentId: "s345678",
    teacherId: "d345678",
    description: "This study focuses on the study, development, and characterization of composite magnetic materials with a primary emphasis on sustainability and their potential application in energy transactions",
    programmes: "Engineering in Civil Engineering",
    title: "Study, development and characterization of composite magnetic materials for sustainability and energy transaction",
    coSupervisors: ["david@example.com", "d567890@polito.it"],
  },
  {
    requestDate: "2020-11-06",
    approvalDate: "",
    approved: null,
    description: "This thesis focuses on the production and application of innovative permanent magnets utilizing both rare earth (RE) elements and rare earth-free alternatives",
    studentId: "s123456",
    teacherId: "d345678",
    title: "Production and application of new permanent magnets, with RE and RE-free",
    type: "Academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "",
    coSupervisors: [],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    type: "stage",
    description: "This thesis explores the innovative preparation of ionogels through photopolymerization, aiming to develop advanced electrolytes for the next generation of lithium batteries",
    notes: "",
    studentId: "s890123",
    teacherId: "d345678",
    title: "Preparation of ionogels via photopolymerization as innovative electrolytes for new generations of lithium batteries",
    programmes: "Architecture",
    coSupervisors: [],
  },
  {
    requestDate: "2020-01-06",
    approvalDate: "",
    approved: null,
    description: "This thesis involves the creation of tangible mathematical objects and the development of a mobile teaching laboratory",
    studentId: "s345678",
    teacherId: "d345678",
    type: "stage",
    notes: "",
    title: "Objects for tangible mathematics and mobile teaching laboratory",
    programmes: "Design in Graphic Design",
    coSupervisors: ["marco@company.com", "alice@example.com"],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    description: "This thesis delves into discrete models to explore how cells undergo reorientation under stress conditions",
    programmes: "Engineering in Civil Engineering",
    notes: "",
    title: "Cellular reorientation under stress: discrete models",
    studentId: "s345678",
    teacherId: "d456789",
    type: "Academic research",
    coSupervisors: ["d234567@polito.it"],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    studentId: "s890123",
    teacherId: "d456789",
    description: "This thesis focuses on developing models and control strategies for elastic microswimmers",
    title: "Modeling and control of elastic microswimmers",
    notes: "",
    programmes: "Engineering in Electrical Engineering",
    type: "Academic research",
    coSupervisors: [],
  },
  {
    requestDate: "2020-08-06",
    approvalDate: "",
    approved: null,
    description: "This thesis explores the development of deep learning algorithms for medical image segmentation, drawing inspiration from domain experts",
    programmes: "Computer Enginnering",
    studentId: "s789012",
    teacherId: "d456789",
    title: "Domain expert-inspired segmentation deep learning algorithms on medical images",
    type: "Academic research",
    notes: "",
    coSupervisors: [],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    type: "Academic research",
    title: "Theory enhanced traffic prediction using Graph Neural Networks",
    studentId: "s789012",
    teacherId: "d567890",
    description: "This thesis investigates the application of Graph Neural Networks to enhance traffic prediction by incorporating theoretical principles",
    programmes: "Engineering in Electrical Engineering",
    notes: "",
    coSupervisors: [],
  },
  {
    requestDate: "2020-11-06",
    approvalDate: "",
    approved: null,
    description: "This thesis focuses on automating and optimizing the configuration of secure communications within virtualized networks",
    type: "stage",
    notes: "",
    programmes: "Engineering in Electrical Engineering",
    title: "Automatic and optimized configuration of secure communications in virtualized networks",
    studentId: "s012345",
    teacherId: "d567890",
    coSupervisors: ["d234567@polito.it", "d345678@polito.it"],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    title: "Design and implementation of a verifier for compiling eBPF code",
    notes: "",
    description: "This thesis centers on designing and implementing a verifier for compiling eBPF (extended Berkeley Packet Filter) code",
    type: "Stage",
    programmes: "Architecture",
    studentId: "s012345",
    teacherId: "d345678",
    coSupervisors: ["marco@company.com", "alice@example.com"],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    description: "This thesis conducts a vulnerability assessment of automotive systems, focusing on identifying and mitigating potential security risks",
    studentId: "s567890",
    teacherId: "d567890",
    title: "Vulnerability Assessment of Automotive Systems",
    type: "Academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "",
    coSupervisors: ["marco@company.com", "d567890@polito.it"],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    description: "This thesis introduces ARMADA, a groundbreaking framework designed for the automatic debugging and repair of hardware designs",
    studentId: "s567890",
    teacherId: "d345678",
    title: "ARMADA: A Framework for Automatic Hardware Design Debugging and Repair",
    type: "Academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "",
    coSupervisors: ["alice@example.com", "d567890@polito.it"],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    description: "This thesis focuses on stress testing chatbots, specifically evaluating their performance in terms of factual accuracy, reasoning abilities, abstraction skills, and addressing other safety challenges",
    studentId: "s234567",
    teacherId: "d234567",
    title: "Stress testing chatbots: evaluating factuality, reasoning, abstraction, and other safety challenges",
    type: "Academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "",
    coSupervisors: []
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    description: "This thesis explores data-centric approaches in AI, focusing on the augmentation techniques for improving bias mitigation and enhancing data quality",
    studentId: "s234567",
    teacherId: "d456789",
    title: "Data-centric AI: Dataset augmentation techniques for bias and data quality improvement",
    type: "Academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "",
    coSupervisors: []
  },
];

export default thesisRequests;
