const thesisRequests = [
  {
    requestDate: "2021-05-06",
    approvalDate: "2021-05-07",
    approved: true,
    title:
      "Caratterizzazione Microstrutturale di Componenti per un Infrastruttura Lunare",
    description: "Description for Thesis Request 1",
    programmes: "Design in Graphic Design",
    studentId: "s345678",
    teacherId: "d345678",
    notes: "Additional notes for Thesis Request 1",
    type: "academic research",
    coSupervisors: [],
  },
  {
    requestDate: "2023-12-06",
    approvalDate: "2023-12-31",
    approved: true,
    type: "academic research",
    notes: "Additional notes for Thesis Request 2",
    studentId: "s345678",
    teacherId: "d345678",
    description: "Description for Thesis Request 2",
    programmes: "Engineering in Civil Engineering",
    title:
      "Studio, sviluppo e caratterizzazione di materiali magnetici compositi per la sostenibilità e transazione energetica",
    coSupervisors: ["david@example.com", "d567890@polito.it"],
  },
  {
    requestDate: "2020-11-06",
    approvalDate: "2020-11-07",
    approved: true,
    description: "Description for Thesis Request 1",
    studentId: "s123456",
    teacherId: "d345678",
    title:
      "Produzione e applicazione dei nuovi magneti permanenti, con RE e RE-free",
    type: "academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "Additional notes for Thesis Request 1",
    coSupervisors: [],
  },
  {
    requestDate: "2023-12-06",
    approvalDate: "2023-12-31",
    approved: true,
    type: "stage",
    description: "Description for Thesis Request 2",
    notes: "Additional notes for Thesis Request 2",
    studentId: "s890123",
    teacherId: "d345678",
    title:
      "Preparazione di ionogel tramite fotopolimerizzazione come elettroliti innovativi per nuove generazioni di batterie al litio",
    programmes: "Architecture",
    coSupervisors: [],
  },
  {
    requestDate: "2021-01-06",
    approvalDate: "",
    approved: null,
    description: "Description for Thesis Request 1",
    studentId: "s345678",
    teacherId: "d345678",
    type: "stage",
    notes: "Additional notes for Thesis Request 1",
    title:
      "Oggetti per una matematica tangibile e laboratorio didattico mobile",
    programmes: "Design in Graphic Design",
    coSupervisors: ["marco@company.com", "alice@example.com"],
  },
  {
    requestDate: "2023-12-06",
    approvalDate: "2023-12-31",
    approved: true,
    description: "Description for Thesis Request 2",
    programmes: "Engineering in Civil Engineering",
    notes: "Additional notes for Thesis Request 2",
    title:
      "Riorientazione cellulare sotto sforzo: modelli discreti",
    studentId: "s345678",
    teacherId: "d456789",
    type: "academic research",
    coSupervisors: ["d234567@polito.it"],
  },
  {
    requestDate: "2022-12-06",
    approvalDate: "",
    approved: null,
    studentId: "s890123",
    teacherId: "d456789",
    description: "Description for Thesis Request 1",
    title:
      "Modellizzazione e controllo di micronuotatori elastici",
    notes: "Additional notes for Thesis Request 1",
    programmes: "Engineering in Electrical Engineering",
    type: "academic research",
    coSupervisors: [],
  },
  {
    requestDate: "2021-08-06",
    approvalDate: "",
    approved: null,
    description: "Description for Thesis Request 2",
    programmes: "Architecture",
    studentId: "s789012",
    teacherId: "d456789",
    title:
      "Domain expert-inspired segmentation deep learning algorithms on medical images",
    type: "academic research",
    notes: "Additional notes for Thesis Request 2",
    coSupervisors: [],
  },
  {
    requestDate: "2020-12-06",
    approvalDate: "",
    approved: null,
    type: "academic research",
    title:
      "Theory enhanced traffic prediction using Graph Neural Networks",
    studentId: "s789012",
    teacherId: "d567890",
    description: "Description for Thesis Request 1",
    programmes: "Engineering in Electrical Engineering",
    notes: "Additional notes for Thesis Request 1",
    coSupervisors: [],
  },
  {
    requestDate: "2023-11-06",
    approvalDate: "",
    approved: null,
    description: "Description for Thesis Request 2",
    type: "stage",
    notes: "Additional notes for Thesis Request 2",
    programmes: "Engineering in Electrical Engineering",
    title:
      "Configurazione automatica e ottimizzata di comunicazioni sicure in reti virtualizzate",
    studentId: "s012345",
    teacherId: "d567890",
    coSupervisors: ["d234567@polito.it", "d345678@polito.it"],
  },
  {
    requestDate: "2023-12-06",
    approvalDate: "",
    approved: null,
    title:
      "Progetto ed implementazione di un verificatore per la compilazione di codice eBPF",
    notes: "",
    description: "Tesi in azienda",
    type: "Stage",
    programmes: "Architecture",
    studentId: "s012345",
    teacherId: "d345678",
    coSupervisors: ["marco@company.com", "alice@example.com"],
  },
  {
    requestDate: "2023-12-06",
    approvalDate: "2023-12-31",
    approved: true,
    description: "Description for Thesis Request 2",
    studentId: "s567890",
    teacherId: "d567890",
    title: "Vulnerability Assessment di Sistemi Automotive",
    type: "academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "Additional notes for Thesis Request 2",
    coSupervisors: ["marco@company.com", "d567890@polito.it"],
  },
  {
    requestDate: "2023-12-06",
    approvalDate: "",
    approved: null,
    description: "Description for Thesis Request 3",
    studentId: "s567890",
    teacherId: "d345678",
    title: "ARMADA: A Framework for Automatic Hardware Design Debugging and Repair",
    type: "academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "Additional notes for Thesis Request 3",
    coSupervisors: ["alice@example.com", "d567890@polito.it"],
  },
  {
    requestDate: "2023-12-06",
    approvalDate: "2023-12-31",
    approved: true,
    description: "Description for Thesis Request 4",
    studentId: "s234567",
    teacherId: "d234567",
    title: "Stress testing chatbots: evaluating factuality, reasoning, abstraction, and other safety challenges",
    type: "academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "Additional notes for Thesis Request 4",
    coSupervisors: []
  },
  {
    requestDate: "2023-12-06",
    approvalDate: "",
    approved: null,
    description: "Description for Thesis Request 5",
    studentId: "s234567",
    teacherId: "d456789",
    title: "Data-centric AI: Dataset augmentation techniques for bias and data quality improvement",
    type: "academic research",
    programmes: "Engineering in Electrical Engineering",
    notes: "Additional notes for Thesis Request 5",
    coSupervisors: []
  },
];

export default thesisRequests;
