const thesisRequests = [
    {
        "requestDate": "2021-05-06",
        "approvalDate": "",
        "approved": null,
        "title": "Instrumenting Kubernetes 5G services with eBPF probes and other beautiful things",
        "description": "Description for Thesis Request 1",
        "programmes": "Design in Graphic Design",
        "level": "master",
        "id": 0,
        "studentId": "s345678",
        "teacherId": "d123456",
        "notes": "Additional notes for Thesis Request 1",
        "type": "academic research"
    },
    {
        "requestDate": "2023-12-06",
        "approvalDate": "2023-12-31",
        "approved": true,
        "level": "master",
        "type": "academic research",
        "notes": "Additional notes for Thesis Request 2",
        "studentId": "s345678",
        "teacherId": "d123456",
        "description": "Description for Thesis Request 2",
        "programmes": "Engineering in Civil Engineering",
        "title": "Sviluppo e containerizzazione di microservizi di monitoraggio e analisi dei consumi energetici su cluster Kubernetes",
        "id": 1,

    },
    {
        "requestDate": "2020-11-06",
        "approvalDate": "",
        "approved": null,
        "description": "Description for Thesis Request 1",
        "level": "bachelor",
        "studentId": "s123456",
        "teacherId": "d234567",
        "title": "Endless scalability of CPU-hungry applications across multiple federated clusters (Liqo/Aruba)",
        "type": "academic research",
        "programmes": "Engineering in Electrical Engineering",
        "notes": "Additional notes for Thesis Request 1",
        "id": 2
    },
    {
        "requestDate": "2023-12-06",
        "approvalDate": "2023-12-31",
        "approved": true,
        "type": "stage",
        "id": 3,
        "level": "bachelor",
        "description": "Description for Thesis Request 2",
        "notes": "Additional notes for Thesis Request 2",
        "studentId": "s890123",
        "teacherId": "d234567",
        "title": "Formal Verification of Safety-Critical Software Systems Using Model Checking Techniques",
        "programmes": "Architecture",
    },
    {
        "requestDate": "2021-01-06",
        "approvalDate": "",
        "approved": null,
        "level": "master",
        "id": 4,
        "description": "Description for Thesis Request 1",
        "studentId": "s345678",
        "teacherId": "d345678",
        "type": "stage",
        "notes": "Additional notes for Thesis Request 1",
        "title": "Automatic and Optimal Configuration of Secure Communications in Virtualized Networks",
        "programmes": "Design in Graphic Design",
    },
    {
        "requestDate": "2023-12-06",
        "approvalDate": "2023-12-31",
        "approved": true,
        "description": "Description for Thesis Request 2",
        "programmes": "Engineering in Civil Engineering",
        "notes": "Additional notes for Thesis Request 2",
        "title": "Utilizing Machine Learning Techniques for Predictive Maintenance of Metallurgical Equipment",
        "level": "master",
        "id": 5,
        "studentId": "s345678",
        "teacherId": "d345678",
        "type": "academic research"
    },
    {
        "requestDate": "2022-12-06",
        "approvalDate": "",
        "approved": null,
        "studentId": "s890123",
        "teacherId": "d456789",
        "description": "Description for Thesis Request 1",
        "level": "bachelor",
        "id": 6,
        "title": "Enhancing Software Quality Through Automated Testing and Continuous Integration",
        "notes": "Additional notes for Thesis Request 1",
        "programmes": "Engineering in Electrical Engineering",
        "type": "academic research"
    },
    {
        "requestDate": "2021-08-06",
        "approvalDate": "",
        "approved": null,
        "description": "Description for Thesis Request 2",
        "programmes": "Architecture",
        "studentId": "s789012",
        "teacherId": "d456789",
        "title": "Definizione dell’infrastruttura di comunicazione e computing per l’operatività di droni/rover su Marte (POLITO/PIC4SER)",
        "id": 7,
        "type": "academic research",
        "notes": "Additional notes for Thesis Request 2",
        "level": "bachelor",
    },
    {
        "requestDate": "2020-12-06",
        "approvalDate": "",
        "approved": null,
        "type": "academic research",
        "title": "Evaluation of Sustainable Construction Materials for Eco-Friendly Building Design",
        "id": 8,
        "studentId": "s789012",
        "teacherId": "d567890",
        "level": "bachelor",
        "description": "Description for Thesis Request 1",
        "programmes": "Engineering in Electrical Engineering",
        "notes": "Additional notes for Thesis Request 1",
    },
    {
        "requestDate": "2023-11-06",
        "approvalDate": "",
        "approved": null,
        "level": "bachelor",
        "description": "Description for Thesis Request 2",
        "id": 9,
        "type": "stage",
        "notes": "Additional notes for Thesis Request 2",
        "programmes": "Engineering in Electrical Engineering",
        "title": "Formal Methods for Software Specification and Verification: Ensuring System Correctness and Reliability",
        "studentId": "s012345",
        "teacherId": "d567890",
    },
    {
        "requestDate": "2023-12-06",
        "approvalDate": "",
        "approved": null,
        "title": "Reply: Investigation of AI-Powered Robotics for Automated Manufacturing Processes",
        "id": 25,
        "notes": "",
        "description": "Tesi in azienda",
        "type": "Stage",
        "programmes": "Architecture",
        "studentId": "s012345",
        "teacherId": "d345678",
        "level": "bachelor"
    },
    {
        "requestDate": "2023-12-06",
        "approvalDate": "2023-12-31",
        "approved": true,
        "description": "Description for Thesis Request 2",
        "level": "bachelor",
        "studentId": "s567890",
        "teacherId": "d567890",
        "title": "Optimizing Deep Learning Models for Edge Devices",
        "type": "academic research",
        "programmes": "Engineering in Electrical Engineering",
        "notes": "Additional notes for Thesis Request 2",
        "id": 26
    },
    {
        "requestDate": "2023-12-06",
        "approvalDate": "",
        "approved": null,
        "description": "Description for Thesis Request 3",
        "level": "bachelor",
        "studentId": "s567890",
        "teacherId": "d345678",
        "title": "Autonomous Robot Navigation using Machine Learning",
        "type": "academic research",
        "programmes": "Engineering in Electrical Engineering",
        "notes": "Additional notes for Thesis Request 3",
        "id": 27
    },
    {
        "requestDate": "2023-12-06",
        "approvalDate": "2023-12-31",
        "approved": true,
        "description": "Description for Thesis Request 4",
        "level": "bachelor",
        "studentId": "s234567",
        "teacherId": "d234567",
        "title": "Enhancing Network Security with Blockchain",
        "type": "academic research",
        "programmes": "Engineering in Electrical Engineering",
        "notes": "Additional notes for Thesis Request 4",
        "id": 28
    },
    {
        "requestDate": "2023-12-06",
        "approvalDate": "",
        "approved": null,
        "description": "Description for Thesis Request 5",
        "level": "bachelor",
        "studentId": "s234567",
        "teacherId": "d456789",
        "title": "Scalable Cloud Solutions for Web Applications",
        "type": "academic research",
        "programmes": "Engineering in Electrical Engineering",
        "notes": "Additional notes for Thesis Request 5",
        "id": 29
    }
]

export default thesisRequests;